---
abstract: 'extend retring-code'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Retry-Extended
provides:
  Sub::Retry::Extended:
    file: lib/Sub/Retry/Extended.pm
    version: 0.02
requires:
  Carp: 0
  Exporter: 0
  Time::HiRes: 0
  parent: 0
  perl: 5.008001
resources:
  bugtracker: http://github.com/bayashi/Sub-Retry-Extended/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/Sub-Retry-Extended
version: 0.02
